# Generated by Django 6.0.6 on 2026-06-23 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmissions_app', '0003_userprofile_ai_query_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_month_accumulated_co2_kg',
            new_name='cumulative_offset_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_carbon_budget_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_tier',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.CreateModel(
            name='RouteSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origin_name', models.CharField(max_length=255)),
                ('destination_name', models.CharField(max_length=255)),
                ('total_distance_km', models.FloatField()),
                ('carbon_emitted_kg', models.FloatField()),
                ('carbon_saved_kg', models.FloatField()),
                ('is_offset', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneInterceptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField()),
                ('mode', models.CharField(choices=[('DRIVE', 'Drive (ICE)'), ('PARK_AND_RIDE', 'Park & Ride Intercept'), ('ELECTRIC_MOTORCYCLE', 'Electric Motorcycle'), ('UBER', 'Uber (Hailing)'), ('WALK', 'Walk')], max_length=30)),
                ('instruction', models.TextField()),
                ('distance_km', models.FloatField()),
                ('emissions_kg', models.FloatField()),
                ('route_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='emmissions_app.routesearchlog')),
            ],
            options={
                'ordering': ['step_index'],
            },
        ),
    ]
