# Generated by Django 6.0.6 on 2026-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmissions_app', '0004_rename_current_month_accumulated_co2_kg_userprofile_cumulative_offset_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_month_accumulated_co2_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_carbon_budget_kg',
            field=models.FloatField(default=300.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
