# Generated by Django 6.0.6 on 2026-06-24 09:37

import emmissions_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmissions_app', '0005_userprofile_current_month_accumulated_co2_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expiry_date',
            field=models.DateTimeField(default=emmissions_app.models.get_default_expiry),
        ),
    ]
