# Generated by Django 6.0.6 on 2026-07-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmissions_app', '0006_userprofile_mpesa_checkout_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcomplaint',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcomplaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('addressed', 'Addressed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='systemcomplaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('transportation', 'Transportation'), ('home_energy', 'Home Energy'), ('diet', 'Diet'), ('payment', 'Payment'), ('offset', 'Carbon Offset')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_type', models.CharField(choices=[('subscription', 'Premium Subscription'), ('carbon_credits', 'Carbon Credits')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_checkout_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mpesa_checkout_id'], name='emmissions__mpesa_c_3e9209_idx'), models.Index(fields=['user', 'status'], name='emmissions__user_id_29be87_idx')],
            },
        ),
    ]
